### ISSUE TITLE
Error when using download tag

### ISSUE THREAD

**Issue by pmoignard** [edalzell/statamic-download#2]
Got a private asset folder set up with it with some assets in there. Your docs say that the "file" attribute on the {{ download }} tag takes the "file name". But when I put that in, I get an error that says:

_"array_key_exists(): The first argument should be either a string or an integer"_

Does "file name" mean what I think it means? Right now I've got {{ download file="download.pdf" }}. Is that the expected value?

**Comment by edalzell** [comment]
Fixed in https://github.com/edalzell/statamic-download/commit/9f122612df5b43ff9ac2cdf1002f00b8b8540de0
